import Head from "next/head";
import React, { PropsWithChildren } from "react";

export const Layout = ({ children }: PropsWithChildren) => (
  <>
    <Head>
      <title>Chirp app</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex h-screen w-screen items-center justify-center">
      {children}
    </main>
  </>
);
